[package]
name = "runtime"
version = "0.1.0"
edition = "2021"

[lib]
name = "runtime"
crate-type = ["staticlib"]

[dependencies]
libc = "0.2"

[profile.release]
opt-level = 3
lto = true
panic = "abort"